### PR TITLE
Creating IsPrime function

### PR DESCRIPTION
**Pull request by Moealfadil**
A function to check whether a number is prime

### CODE REVIEW

**Comment by TagwaHashim** [comment]
دي اول function ليك في ال challenge ؟؟؟

**Comment by Moealfadil** [comment]
ااي

**Review by Luyando-Chitindi — COMMENTED** [review]
please check your py formatting and py tests. Thanks!

**Review by Luyando-Chitindi — APPROVED** [review]
Well formatted and It passed all the checks!

**Pull request merged**
